name = "sublink-worker-admin"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sublink-db" # <-- 请确保这是您在Cloudflare上创建的D1数据库的名称
database_id = "83fbb0e3-254d-41ff-b1c4-0031b614e454" # <-- 请务必将这里替换为您真实D1数据库的ID


